**Problem-1** salary prediction



In [ ]:
# simple linear regression for salary prediction
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
# dummy data - X must be 2d array else sklearn throws error
X = np.array([[1.1], [1.5], [2.0], [2.5], [3.0]])  # exp
y = np.array([40000, 45000, 52000, 60000, 65000])  # salary

In [ ]:
# training
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [ ]:
# checking parameters (y = mx + c)
# note: trailing underscore means values are learned after fitting
m = model.coef_[0]
c = model.intercept_
print(f"equation: y = {m:.2f}*x + {c:.2f}")

equation: y = 13544.19*x + 25040.73


In [ ]:
# test prediction
# need double brackets here to avoid valueerror shape issue
test_exp = [[2.8]]
pred = model.predict(test_exp)
print(f"pred for 2.8 yrs: {pred[0]:.2f}")

pred for 2.8 yrs: 62964.47


In [ ]:
# evaluation
y_pred = model.predict(X)
print("mse:", mean_squared_error(y, y_pred))
print("r2:", r2_score(y, y_pred))

mse: 361698.440207974
r2: 0.9957467257736597


**Problem-2** Telecom company


In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix


In [ ]:
#data setup(X=age,monthly bill y=Churn(stay=0 ,1=leave)
X=np.array([[21,50],[45,110],[30,60],[55,120],[23,45]])
y=np.array([0,1,0,1,0])


In [ ]:
#Train classification engine
model=LogisticRegression()
model.fit(X,y)


LogisticRegression()

In [ ]:
#live prediction for new customer(age=40,monthly bill=95)
new_user=[[40,95]]
pred=model.predict(new_user)
print=(f"churn prediction for {new_user[0]}:{pred[0]}")

In [ ]:
#Evaluation matrix
y_pred=model.predict(X)
print("Accuracy score:",accuracy_score(y,y_pred))
print("Confusion matrix: ",confusion_matrix(y,y_pred))

Accuracy score: 1.0
Confusion matrix:  [[3 0]
 [0 2]]


**Problem-3** Data preprocessing

In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
#Raw messy data set
raw_data={
    'Experience':[2.5,np.nan,5.0,1.2,np.nan,4.0],
    'Department':['IT','HR','IT','Sales',np.nan,'HR'],
    'Salary':[50000,35000,42000,70000,44000,66000]
}

In [ ]:
df=pd.DataFrame(raw_data)
print("Before preprocessing (messy data) ",df)

Before preprocessing (messy data)     Experience Department  Salary
0         2.5         IT   50000
1         NaN         HR   35000
2         5.0         IT   42000
3         1.2      Sales   70000
4         NaN        NaN   44000
5         4.0         HR   66000


In [ ]:
#Handle Missing Numericals Values using Mean
num_imputer=SimpleImputer(strategy='mean')
df['Experience']=num_imputer.fit_transform(df[['Experience']])


In [ ]:
#Handle Missing Categorical Values using Mode Frequent(Mode)
cat_imputer=SimpleImputer(strategy='most_frequent')
df['Department']=cat_imputer.fit_transform(df[['Department']]).ravel()

In [ ]:
#One-Hot Encodeing for Text categories(Sales,IT,HR)
encoder=OneHotEncoder(sparse_output=False)
encoder_dept=encoder.fit_transform(df[['Department']])

In [ ]:
print("After Imputation(Numerical cleaned)",df ['Experience'].values)
print("One-Hot Encoded Department",encoder_dept)

After Imputation(Numerical cleaned) [2.5   3.175 5.    1.2   3.175 4.   ]
One-Hot Encoded Department [[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


**Problem 4** K-mwans clustering

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans


In [2]:
#Customer profile(Annual Income in lakhs,spending score 1-100 )
X=np.array([[15,39],[15,81],[19,6],[40,72],[47,40],[54,55],[78,17],[88,91]])

In [3]:
#Configure KMeans to form 3 distinct groups
#Note:n_init='auto' ensures modern scikit-learn compliance
kmeans=KMeans(n_clusters=3,random_state=42,n_init='auto')
y_clusters=kmeans.fit_predict(X)

In [4]:
print("Customer Group Assignment: ",y_clusters)
print("Calculate CLusters Centers: ",kmeans.cluster_centers_)

Customer Group Assignment:  [0 2 0 2 0 2 0 1]
Calculate CLusters Centers:  [[39.75       25.5       ]
 [88.         91.        ]
 [36.33333333 69.33333333]]


**Problem 5** Loan approval System (Decision tree classifier)


In [5]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text

In [6]:
#X=[Credit score,income in lakhs],y=Approved(1=yes,2=no)
X=np.array([[600,5],[750,12],[500,3],[710,8],[680,4]])
y=np.array([0,1,0,1,0])

In [9]:
#Train decision tree
tree_model=DecisionTreeClassifier(criterion='entropy',random_state=42)
tree_model.fit(X,y)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [10]:
#text output of logic tree splits
tree_rules=export_text(tree_model,feature_names=['credit_score','Income'])
print("Internal Decision tree rules",tree_rules)

Internal Decision tree rules |--- credit_score <= 695.00
|   |--- class: 0
|--- credit_score >  695.00
|   |--- class: 1

